### PR TITLE
Allow including environment variables as defines.

### PR DESCRIPTION
**Pull request by bittrance**
Allow including defines from local environment, e.g.:
```
$ echo '{{ TERM }}' | jinja --defines-from-env
xterm-256color
```
You can also filter environment vars to include `jinja --defines-from-env='^AWS_'`.

This is very useful in a Docker context, where you can now pass environment vars directly from your Swarm or Kubernetes stack definition into a template without having to explicitly enumerate them in your Dockerfile or wrapper script where jinja is run.

### CODE REVIEW

**Comment by ollofx** [comment]
Hi @bittrance, 

I find the feature you are suggesting very useful, will it be possible to also contribute to this [package](https://github.com/mattrobenolt/jinja2-cli)  with it ?

Thank you

**Comment by bittrance** [comment]
@ollofx Feel free to merge the defines-from-env branch on bittrance/jinja-cli repo into your repository. You can create pull requests with branches from any repository in the network by pressing the "compare across forks" link on the new pull request page.

**Comment by cykerway** [comment]
Hi, just to let you know that this PR has been merged at https://github.com/cykerway/jinja-cli/commit/21200b51cecf934fea0ef38855e7625bb56e8756. But for some reason the commit log in your repo became disorder. I'm sorry about that and you can revert those changes in your repo if you want, or delete your entire feature branch. I wasn't very interested with these online tools and the merge was actually done using CLI. Somehow the web interface doesn't recognize this merge.

I'll abandon this PR since it has been successfully merged. If you know where I did wrong (likely an extra rebase?) you can leave a comment below. Thank your for this feature suggestion.

**Comment by cykerway** [comment]
FYI I think `--defines-from-env` is too long and so shortened it into `-X, --env-regex`. You should be able to use something like `jinja -X '^AWS_'` now.

**Comment by ollofx** [comment]
Hi @cykerway @bittrance 
found this fork, https://github.com/kolypto/j2cli , I've not checked extensively all the features but there is an interesting approach of defining {{ env(VAR) }} within your template.

**Pull request closed without merging**
